SEO-3239 ASP.NET MVC Page with redirect
syncfusion-content/asp.netmvc-docs pull request #277
Opened 2023-02-14 10:25 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Please review the changes for ASP.NET MVC Page with redirect.

Regards,
Yvone.

2023-02-14 10:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3239-ASP.NET-MVC-Page-with-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/console)**

2023-02-14 10:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3239-ASP.NET-MVC-Page-with-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/121/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-15 04:45 UTC, gowthamanthavasiyappan requested changes

2023-02-15 04:45 UTC, gowthamanthavasiyappan commented on aspnetmvc/Grid/How-to.md
> +# How to Section in ASP.NET MVC
Add Control name in H1 tag

2023-02-16 06:14 UTC, gowthamanthavasiyappan commented
Commented

2023-02-16 06:28 UTC, Yvone-Atieno commented on aspnetmvc/Grid/How-to.md
> +# How to Section in ASP.NET MVC
added control name

2023-02-16 06:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3239-ASP.NET-MVC-Page-with-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/console)**

2023-02-16 06:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3239-ASP.NET-MVC-Page-with-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/123/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-16 07:16 UTC, gowthamanthavasiyappan approved these changes

2023-02-21 07:04 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-02-21 07:04 UTC, merged