SEO-3260-MVC-Description-Too-Short
syncfusion-content/asp.netmvc-docs pull request #279
Opened 2023-02-15 14:05 UTC by berylouma

Hi @Aishwarya-Ganesan 

I have worked on the descriptions. 

Regards,
Beryl

2023-02-15 14:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3260-MVC-Description](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/console)**

2023-02-15 14:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3260-MVC-Description](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/122/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-21 06:13 UTC, gowthamanthavasiyappan requested changes

2023-02-21 06:13 UTC, gowthamanthavasiyappan commented on aspnetmvc/Grid/How-to.md
> +# ASP.NET MVC Grid
H1 tag length should be above 20 to below 70 characters, so change

2023-03-02 05:33 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-3260-MVC-Description](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/console)**

2023-03-02 05:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3260-MVC-Description](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/console)**

2023-03-02 05:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3260-MVC-Description](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/136/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-02 05:36 UTC, berylouma commented on aspnetmvc/Grid/How-to.md
> +# ASP.NET MVC Grid
Resolved

2023-04-24 08:31 UTC, closed without merging