SEO-3569 ASP.NET MVC Site Audit Issues
syncfusion-content/asp.netmvc-docs pull request #302
Opened 2023-04-05 14:28 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Have changed title, description, H1 and named images.

Regards,
Yvone.

2023-04-05 14:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3569-ASP.NET-MVC-Issue-fixes](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/142/console)**

2023-04-11 04:12 UTC, gowthamanthavasiyappan requested changes
Commented

2023-04-11 05:05 UTC, Yvone-Atieno commented on aspnetmvc/Autocomplete/How-to.md
> +title: How To Section with ASP.NET MVC TreeView Control | Syncfusion
updated

2023-04-11 05:08 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-3569-ASP.NET-MVC-Issue-fixes](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/143/console)**

2023-04-11 05:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3569-ASP.NET-MVC-Issue-fixes](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/143/console)**

2023-04-11 05:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3569-ASP.NET-MVC-Issue-fixes](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/143/)<br/>**

2023-04-11 11:34 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-04-13 12:17 UTC, Aishwarya-Ganesan commented on aspnetmvc/Button/Overview.md
> +title: Overview in ASP.NET MVC Button Control | Syncfusion
Overview of ASP.NET MVC Button Control - title

2023-04-13 12:18 UTC, Aishwarya-Ganesan commented on aspnetmvc/Button/Overview.md
> +# Overview in ASP.NET MVC Button
Overview of ASP.NET MVC Button

2023-04-13 12:18 UTC, Aishwarya-Ganesan commented on aspnetmvc/Gantt/Columns.md
>  title: Columns | Gantt | ASP.NET MVC | Syncfusion
here title is not changed?

2023-04-13 12:25 UTC, Aishwarya-Ganesan reviewed
Commented

2023-04-13 12:31 UTC, Yvone-Atieno commented on aspnetmvc/Button/Overview.md
> +description: Learn here more about Overview in Syncfusion Essential ASP.NET MVC Button Control, its elements, and more.
changed

2023-04-13 12:32 UTC, Yvone-Atieno commented on aspnetmvc/Button/Overview.md
> +# Overview in ASP.NET MVC Button
changed

2023-04-13 12:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3569-ASP.NET-MVC-Issue-fixes](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/145/)<br/>**

2023-04-13 18:01 UTC, merged