SEO-176113-MVC-Missing-H1
syncfusion-content/asp.netmvc-docs pull request #388
Opened 2023-09-22 11:51 UTC by berylouma

Hello,

I have worked on the missing H1

Regards,
Beryl.

2023-09-22 11:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-MVC-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/217/console)**

2023-09-22 11:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-MVC-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/217/)<br/>**

2023-09-26 12:33 UTC, Yvone-Atieno requested changes
Commented

2023-09-26 12:33 UTC, Yvone-Atieno commented on aspnetmvc/DataManager/Antiforgery.md
> +![Antiforgery Token in ASP.NET MVC](Antiforgery_images/Antiforgery.png)
Should include control name also

2023-09-26 12:33 UTC, Yvone-Atieno commented on aspnetmvc/DataManager/Antiforgery.md
> +![Antiforgery Token Value in ASP.NET MVC](Antiforgery_images/Antiforgery_header.png)
Should include control name

2023-09-26 13:25 UTC, berylouma commented on aspnetmvc/DataManager/Antiforgery.md
> +![Antiforgery Token in ASP.NET MVC](Antiforgery_images/Antiforgery.png)
Added

2023-09-26 13:25 UTC, berylouma commented on aspnetmvc/DataManager/Antiforgery.md
> +![Antiforgery Token Value in ASP.NET MVC](Antiforgery_images/Antiforgery_header.png)
Added

2023-09-26 13:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-MVC-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/219/console)**

2023-09-26 13:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-MVC-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/219/)<br/>**

2023-09-26 13:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-MVC-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/220/console)**

2023-09-26 13:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-MVC-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/asp.netmvc-docs/220/)<br/>**

2023-11-10 09:39 UTC, merged