SEO-178901-mvc-page-with-redirect
syncfusion-content/asp.netmvc-docs pull request #410
Opened 2024-01-04 13:08 UTC by Edithabich

Hi @MallikaRK ,
Please review the redirect link changes made
Thanks.

Regards,
Edith.

2024-01-04 13:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178901-mvc-page-with-redirect](https://ci.syncfusion.com/job/Content/job/asp.netmvc-docs/3/console)**

2024-01-04 13:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178901-mvc-page-with-redirect](https://ci.syncfusion.com/job/Content/job/ASP.NETMVC-docs/3/)<br/>**

2024-01-05 08:53 UTC, Yvone-Atieno requested changes
Commented

2024-01-05 08:53 UTC, Yvone-Atieno commented on aspnetmvc/Chart/3D-Chart.md
> +[Click](https://ej2.syncfusion.com/aspnetmvc/ThreeDimensionalChart/StackedColumn#/bootstrap5) here to view the 100% Stacked Column 3DChart online demo sample.
Check the updated link

2024-01-05 08:57 UTC, Edithabich commented on aspnetmvc/Chart/3D-Chart.md
> +[Click](https://ej2.syncfusion.com/aspnetmvc/ThreeDimensionalChart/StackedColumn#/bootstrap5) here to view the 100% Stacked Column 3DChart online demo sample.
resolved

2024-01-05 08:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178901-mvc-page-with-redirect](https://ci.syncfusion.com/job/Content/job/asp.netmvc-docs/4/console)**

2024-01-05 09:03 UTC, SyncfusionBuild commented
The CI [Job](https://ci.syncfusion.com/job/Content/job/asp.netmvc-docs/4/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2024-01-05 09:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178901-mvc-page-with-redirect](https://ci.syncfusion.com/job/Content/job/ASP.NETMVC-docs/4/)<br/>**

2024-01-05 09:05 UTC, Yvone-Atieno approved these changes
Approved

2024-01-16 08:53 UTC, merged